#!/usr/bin/env python
#
# Print song lyrics from https://genius.com/
#
# Usage (Linux):
#   alias xclip="xclip -selection c"
#   ./getlyrics [url] | xclip
#
# Usage (MacOS):
#   ./getlyrics [url] | pbcopy
#

from bs4 import BeautifulSoup
import sys
import requests

if __name__ == '__main__':
    url = sys.argv[1]
    r = requests.get(url)
    html = r.text
    soup = BeautifulSoup(html, 'html.parser')
    lyrics = str(soup.find_all('div', {'class': 'kUgSbL'}))
    for line in lyrics.split('<br/>'):
        print(f'"{line}",')
